[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.3"
ark-serialize = "0.3"  # If you need serialization support
ark-bn254 = "0.3"  # If you need pairing-based cryptography with the BN254 curve
rand = "0.8"
num = "0.4.3"  # Ensure this is the latest version
